[workspace]
members = ["crates/lex-app", "crates/lex-ui", "crates/lex-render", "crates/lex-net", "crates/lex-html"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.80"
authors = ["Lex Contributors"]
license = "MIT"
repository = "https://github.com/CoolgamerProXD/Lex-Browser"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"

[profile.dev]
debug = 1

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
panic = "abort"
