[package]
name = "lex-render"
description = "Platform-independent display commands and graphics backends for Lex"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = [
  "Foundation_Numerics",
  "Win32_Foundation",
  "Win32_Graphics_Direct2D",
  "Win32_Graphics_Direct2D_Common",
  "Win32_Graphics_DirectWrite",
  "Win32_Graphics_Dxgi_Common",
] }

[lints]
workspace = true
